name: Delivery new image

on:
  push:
    branches: ["master"]

jobs:
  make-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git -y
      - name: Tag
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://github.com/antoniopantaleo/docker-vim.git
          git tag -a $(cat VERSION) -m "New version released"
          git push --tags
    
  delivery:
    needs: make-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build and push
        run: |
          docker buildx build --file ./Dockerfile --platform linux/arm64,linux/amd64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 --tag ghcr.io/antoniopantaleo/vim:latest --tag ghcr.io/antoniopantaleo/vim:$(cat VERSION) --push .
