name: Delivery new image

on:
  push:
    branches: ["master"]

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git -y
      - name: Check version
        run: bash .github/check_version.sh
      - name: Tag
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://github.com/antoniopantaleo/docker-vim.git
          git tag -a $(cat VERSION) -m "New version released"
          git push --tags
    
  delivery:
    needs: check-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/antoniopantaleo/vim:latest
